### ISSUE TITLE
Documentation error/possible bug

### ISSUE THREAD

**Issue by JasonTrue** [membraneframework/membrane_opus_plugin#29]
The documentation on hex/in the README mentions `Membrane.Opus.Serializer` which was removed in commit 
@ledhed2222's commit bfd5e2af0fc105daa7b629e029e06d3e277758cf on Thu Mar 18 05:30:56 2021 -0400.
The current expected process is not clear.

I was able to intuit that the `serializer: Membrane.Opus.Serializer` should be replaced with `parser: Membrane.Opus.Parser,` but if I use the pipeline with only that correction and a raw audio file (for example, captured with `ffmpeg -f avfoundation -i ":1" -f s16le -c:2 -f output-s16le-48k-2ch.raw`), the file that is produced doesn't appear to be playable. VLC sees it as an zero-length audio file, and `opusinfo` reports something like the following:

````
Processing file "output-s16le-48k-2ch.opus"...

WARNING: Hole in data (87 bytes) found at approximate offset 4500 bytes. Corrupted Ogg.
WARNING: Hole in data (213 bytes) found at approximate offset 4500 bytes. Corrupted Ogg.
WARNING: Hole in data (343 bytes) found at approximate offset 4500 bytes. Corrupted Ogg.
WARNING: Hole in data (413 bytes) found at approximate offset 4500 bytes. Corrupted Ogg.
WARNING: Hole in data (15 bytes) found at approximate offset 4500 bytes. Corrupted Ogg.
WARNING: Hole in data (238 bytes) found at approximate offset 4500 bytes. Corrupted Ogg.
... (much more of this)
WARNING: Hole in data (137 bytes) found at approximate offset 43424 bytes. Corrupted Ogg.
ERROR: No Ogg data found in file "output-s16le-48k-2ch.opus".
Input probably not Ogg.
````

I slightly modified the README example for encoding (plus some tweaks to the file paths that made sense in my case), using membrane_opus_plugin v0.10.0.

````elixir
  def handle_init(_) do
    children = [
      source: %Membrane.File.Source{
        location: "/tmp/input.raw"
      },
      encoder: %Membrane.Opus.Encoder{
        application: :audio,
        input_caps: %Raw{
          channels: 2,
          format: :s16le,
          sample_rate: 48_000
        }
      },
      serializer: Membrane.Opus.Parser, ### This is where I modified the documentation example
      sink: %Membrane.File.Sink{
        location: "/tmp/output.opus"
      }
    ]

    links = [
      link(:source)
      |> to(:encoder)
      |> to(:serializer)
      |> to(:sink)
    ]

    {{:ok, spec: %ParentSpec{children: children, links: links}}, %{}}
  end
end
````

If it hadn't been for the unusable file at the end I'd just have submitted a documentation pull request, but I can't see a clear path to get a functional file. A similar pipeline using an MP3 plugin seemed to work just fine.

(In the event that it matters, I'm using MacOS on Intel hardware and my colleague is using an M1-based Mac).

**Comment by mat-hek** [comment]
Hi @JasonTrue, as the error suggests, FFmpeg is actually trying to play the file as Ogg, not Opus, because it doesn't support bare Opus AFAIK. If you'd like to get Ogg, see https://github.com/ledhed2222/membrane_ogg_plugin/blob/main/lib/membrane_ogg/payloader/opus.ex. Any PRs with documentation improvements are welcome ;)

**Comment by JasonTrue** [comment]
Right, I captured the audio with ffmpeg but played/analyzed it with "opusinfo." Fair enough. I'll do an experiment with the ogg payloader and I'll send a PR to update the docs WRT the change to use the Parser module if there isn't already one pending.

**Comment by JasonTrue** [comment]
Since the Ogg plugin isn't released and is built against much older versions of membrane it looks like a bit of a challenge to get the dependencies overridden/aligned; I'll see what I can do.
